version: '3.7'
services:
  backend:
    image: node:lts
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    command: bash -c "npm install && npm start"
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/
      - ACCESS_TOKEN_SECRET=$(openssl rand -hex 64)
    depends_on:
      - mongodb

  frontend:
    image: node:lts
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: bash -c "npm install && npm start"
    ports:
      - '4200:4200'
    depends_on:
      - backend

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
