version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - '4200:4200'
    depends_on:
      - backend

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
